DATA:
  name: "Tiny_ImageNet"
  img_size: 64
  num_classes: 200
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "cBN"
  d_cond_mtd: "PD"
  apply_g_sn: true
  apply_d_sn: true
  apply_attn: true
  attn_g_loc: [3]
  attn_d_loc: [1]
  z_dim: 100
  g_shared_dim: 128
  g_conv_dim: 80
  d_conv_dim: 80
  apply_g_ema: true
  g_ema_decay: 0.9999
  g_ema_start: 20000
LOSS:
  adv_loss: "hinge"
OPTIMIZATION:
  batch_size: 1024
  g_lr: 0.0001
  d_lr: 0.0004
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 1
  total_steps: 200000
AUG:
  apply_ada: True
  ada_aug_type: "bgc"
  ada_initial_augment_p: 0
  ada_target: 0.6
  ada_kimg: 500
  ada_interval: 4
