# Guidelines for StyleGAN2-D2DCE-ADA config
# g_cond_mtd can be changed btw ["W/O", "cAdaIN"]
# d_cond_mtd can be changed btw ["W/O", "AC", "PD", "MH", "MD", "2C", "D2DCE", "SPD"]
# z_dim, w_dim should be fixed to 512 regardless of image size.
# apply_g_ema should be true for stable results.
# apply_r1_reg should be true.
# g_reg_interval, d_reg_interval is fixed to 4, 16 regardless of image size.
# pl_reg is disabled only for cifar10.
# d_architecture is 'orig' for cifar10.
# style_mixing_p should be 0.9 for all settings except for cifar10 (0)
# for total_step, batch_size, d_epilogue_mbstd_group_size, g/d_lr, r1_lambda, g_ema_kimg
# g_ema_rampup, mapping_network, check StyleGAN2 section in src/config.py

DATA:
  name: "AFHQ"
  img_size: 512
  # img_size: 420
  num_classes: 3
MODEL:
  backbone: "stylegan2"
  g_cond_mtd: "cAdaIN"
  d_cond_mtd: "D2DCE"
  normalize_d_embed: True
  d_embed_dim: 1024
  g_act_fn: "Auto"
  d_act_fn: "Auto"
  z_prior: "gaussian"
  z_dim: 512
  w_dim: 512
  # z_dim: 420
  # w_dim: 420
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
  apply_g_ema: True
LOSS:
  adv_loss: "logistic"
  cond_lambda: 0.5
  m_p: 0.95
  temperature: 0.5
  apply_r1_reg: True
  r1_lambda: 0.5
OPTIMIZATION:
  # These values will be slightly changed if lazy regularization is applied.
  # batch_size: 64
  # acml_steps: 1
  batch_size: 32
  acml_steps: 2
  g_lr: 0.0025
  d_lr: 0.0025
  beta1: 0
  beta2: 0.99
  g_updates_per_step: 1
  d_updates_per_step: 2
  total_steps: 200000
AUG:
  apply_ada: True
  ada_aug_type: "bgc"
  ada_initial_augment_p: 0
  ada_target: 0.8
  ada_kimg: 500
  ada_interval: 4
STYLEGAN2:
  g_reg_interval: 4
  d_reg_interval: 16
  mapping_network: 8
  style_mixing_p: 0.9
  g_ema_kimg: 20
  g_ema_rampup: "N/A"
  apply_pl_reg: True
  pl_weight: 2
  d_architecture: "resnet"
  d_epilogue_mbstd_group_size: 8
